


/*------ SYSDBA 12/10/2022 10:58:27 --------*/

CREATE INDEX IDX_TBCLIENTE_EMAIL
ON TBCLIENTE (EMAIL);

CREATE INDEX IDX_TBCLIENTE_CELULAR
ON TBCLIENTE (FONECEL);

CREATE INDEX IDX_TBCLIENTE_FONE
ON TBCLIENTE (FONE);

