


/*------ SYSDBA 17/02/2022 09:14:08 --------*/

CREATE INDEX IDX_TBCONTPAG_DATAVENC_ASC
ON TBCONTPAG (DTVENC);

CREATE INDEX IDX_TBCONTPAG_QUITADO
ON TBCONTPAG (QUITADO);

CREATE DESCENDING INDEX IDX_TBCONTPAG_DATAVENC_DESC
ON TBCONTPAG (DTVENC);




/*------ SYSDBA 17/02/2022 09:16:01 --------*/

CREATE INDEX IDX_TBFORNECEDOR_CNPJ
ON TBFORNECEDOR (CNPJ);

