


/*------ SYSDBA 30/08/2018 20:00:30 --------*/

CREATE INDEX IDX_TBCLIENTE_FANTASIA
ON TBCLIENTE (NOMEFANT);

CREATE INDEX IDX_TBCLIENTE_RAZAO
ON TBCLIENTE (NOME);




/*------ SYSDBA 30/08/2018 20:01:17 --------*/

CREATE INDEX IDX_TBFORNECEDOR_FANTASIA
ON TBFORNECEDOR (NOMEFANT);

CREATE INDEX IDX_TBFORNECEDOR_RAZAO
ON TBFORNECEDOR (NOMEFORN);

