program SGE;



{$R *.dres}

uses
  Windows,
  Forms,
  Controls,
  IniFiles,
  SysUtils,
  MidasLIB,
  HPL_Strings in '..\Sys\lib\HPL_Strings.pas',
  UEcfAgil in '..\Sys\lib\UEcfAgil.pas',
  UEcfGenerico in '..\Sys\lib\UEcfGenerico.pas',
  UEcfFactory in '..\Sys\lib\UEcfFactory.pas',
  UPrinc in 'UPrinc.pas' {frmPrinc},
  UDMBusiness in '..\Sys\UDMBusiness.pas' {DMBusiness: TDataModule},
  UPesqProd in '..\Sys\UPesqProd.pas' {frmPesqProd},
  UGrPadraoCadastro in '..\Sys\lib\UGrPadraoCadastro.pas' {frmGrPadraoCadastro},
  UGrPadrao in '..\Sys\lib\UGrPadrao.pas' {frmGrPadrao},
  UGeVenda in '..\Sys\UGeVenda.pas' {frmGeVenda},
  UGrPadraoCadastroSimples in '..\Sys\lib\UGrPadraoCadastroSimples.pas' {frmGrPadraoCadastroSimples},
  UDMNFe in '..\Sys\UDMNFe.pas' {DMNFe: TDataModule},
  UGeVendaGerarNFe in '..\Sys\UGeVendaGerarNFe.pas' {frmGeVendaGerarNFe},
  UGeConfigurarNFeACBr in '..\Sys\UGeConfigurarNFeACBr.pas' {frmGeConfigurarNFeACBr},
  UEnviarLoteNFe in '..\Sys\UEnviarLoteNFe.pas' {frmEnviarLoteNFe},
  UGeVendaCancelar in '..\Sys\UGeVendaCancelar.pas' {frmGeVendaCancelar},
  UGrCampoRequisitado in '..\Sys\lib\UGrCampoRequisitado.pas' {frmCampoRequisitado},
  UGeGerarBoletos in '..\Sys\UGeGerarBoletos.pas' {frmGeGerarBoleto},
  UGeRemessaBoletos in '..\Sys\UGeRemessaBoletos.pas' {frmGeRemessaBoleto},
  UGeRetornoBoletos in '..\Sys\UGeRetornoBoletos.pas' {frmGeRetornoBoleto},
  UGeCaixa in '..\Sys\UGeCaixa.pas' {frmGeCaixa},
  UGeFluxoCaixa in '..\Sys\UGeFluxoCaixa.pas' {frmGeFluxoCaixa},
  UFuncoes in '..\Sys\lib\UFuncoes.pas',
  FormFactoryU in '..\Sys\lib\FormFactoryU.pas',
  FuncoesFormulario in '..\Sys\lib\FuncoesFormulario.pas',
  UConstantesDGE in '..\Sys\UConstantesDGE.pas',
  UGeVendaFormaPagto in '..\Sys\UGeVendaFormaPagto.pas' {frmGeVendaFormaPagto},
  UGeExportarNFeGerada in '..\Sys\UGeExportarNFeGerada.pas' {frmGeExportarNFeGerada},
  UGeVendaTransporte in '..\Sys\UGeVendaTransporte.pas' {frmGeVendaTransporte},
  UGeVendaConfirmaTitulos in '..\Sys\UGeVendaConfirmaTitulos.pas' {frmGeVendaConfirmaTitulos},
  UGrPadraoPesquisa in '..\Sys\lib\UGrPadraoPesquisa.pas' {frmGrPadraoPesquisa},
  UGeVendaItemPesquisa in '..\Sys\UGeVendaItemPesquisa.pas' {FrmGeVendaItemPesquisa},
  UGeProdutoRotatividadePRC in '..\Sys\UGeProdutoRotatividadePRC.pas' {FrmGeProdutoRotatividadePRC},
  UGeInutilizarNumeroNFe in '..\Sys\UGeInutilizarNumeroNFe.pas' {frmGeInutilizarNumeroNFe},
  UGeProdutoEstoqueMinimo in 'UGeProdutoEstoqueMinimo.pas' {FrmGeProdutoEstoqueMinimo},
  UObserverInterface in '..\Sys\lib\UObserverInterface.pas',
  UBaseObject in '..\Sys\lib\UBaseObject.pas',
  UCliente in '..\Sys\lib\UCliente.pas',
  UGrPadraoImpressao in 'lib\UGrPadraoImpressao.pas' {frmGrPadraoImpressao},
  UGeClienteImpressao in 'UGeClienteImpressao.pas' {frmGeClienteImpressao},
  UGeEstoqueAjusteManual in 'UGeEstoqueAjusteManual.pas' {frmGeEstoqueAjusteManual},
  UGeRequisicaoCliente in 'UGeRequisicaoCliente.pas' {frmGeRequisicaoCliente},
  UGeVendaImpressao in 'UGeVendaImpressao.pas' {frmGeVendaImpressao},
  UGeExportarChaveNFeGerada in '..\Sys\UGeExportarChaveNFeGerada.pas' {frmGeExportarChaveNFeGerada},
  UGeExportarNFC in '..\Sys\UGeExportarNFC.pas' {frmGeExportarNFC},
  UGeContasAReceberImpressao in 'UGeContasAReceberImpressao.pas' {frmGeContasAReceberImpressao},
  UGrConfigurarAmbiente in '..\Sys\lib\UGrConfigurarAmbiente.pas' {frmGrConfigurarAmbiente},
  UGeContasAPagarImpressao in 'UGeContasAPagarImpressao.pas' {frmGeContasAPagarImpressao},
  UGeEntradaImpressao in 'UGeEntradaImpressao.pas' {frmGeEntradaImpressao},
  UEcfWindowsPrinter in '..\Sys\lib\UEcfWindowsPrinter.pas',
  UGeFornecedorImpressao in 'UGeFornecedorImpressao.pas' {frmGeFornecedorImpressao},
  UGrRegistroEstacao in '..\Sys\lib\UGrRegistroEstacao.pas' {FrmGrRegistroEstacao},
  UGeRequisicaoCompraPesquisa in 'UGeRequisicaoCompraPesquisa.pas' {frmGeRequisicaoCompraPesquisa},
  UGeCartaCorrecao in '..\Sys\UGeCartaCorrecao.pas' {frmGeCartaCorrecao},
  UGeProdutoKardex in '..\Sys\UGeProdutoKardex.pas' {frmGeProdutoKardex},
  UEcfBematechNaoFiscal in '..\Sys\lib\UEcfBematechNaoFiscal.pas',
  UDMRecursos in '..\Sys\UDMRecursos.pas' {DMRecursos: TDataModule},
  UGeInventario in '..\System_SGI\UGeInventario.pas' {frmGeInventario},
  UGeVendaDevolucaoNF in '..\Sys\UGeVendaDevolucaoNF.pas' {frmGeVendaDevolucaoNF},
  UGrConfigurarBackup in '..\Sys\lib\UGrConfigurarBackup.pas' {frmGrConfigurarBackup},
  UGeProdutoImpressao in 'UGeProdutoImpressao.pas' {frmGeProdutoImpressao},
  UGeProdutoEstoqueImpressao in 'UGeProdutoEstoqueImpressao.pas' {frmGeProdutoEstoqueImpressao},
  UGeNFComplementar in '..\Sys\UGeNFComplementar.pas' {frmGeNFComplementar},
  UGeFluxoCaixaImpressao in '..\Sys\UGeFluxoCaixaImpressao.pas' {frmGeFluxoCaixaImpressao},
  Model.Licenca in '..\GerarLicenca\Model\Model.Licenca.pas',
  Model.Usuario in '..\GerarLicenca\Model\Model.Usuario.pas',
  Model.Endereco in '..\GerarLicenca\Model\Model.Endereco.pas',
  Model.Cliente in '..\GerarLicenca\Model\Model.Cliente.pas',
  Controller.Interfaces in '..\GerarLicenca\Controller\Controller.Interfaces.pas',
  Controller.UsuarioApp in '..\GerarLicenca\Controller\Controller.UsuarioApp.pas',
  Controller.ClienteApp in '..\GerarLicenca\Controller\Controller.ClienteApp.pas',
  Controller.FactoryApp in '..\GerarLicenca\Controller\Controller.FactoryApp.pas',
  View.Memo in '..\Sys\View\View.Memo.pas' {ViewMemo},
  View.MemoData in '..\Sys\View\View.MemoData.pas' {ViewMemoData},
  View.Mensagem in '..\Sys\View\View.Mensagem.pas' {FrmMensagem},
  View.PadraoAbertura in '..\Sys\View\View.PadraoAbertura.pas' {FrmPadraoAbertura},
  View.Abertura in 'View\View.Abertura.pas' {FrmAbertura},
  View.AutoUpgrade in '..\Sys\View\View.AutoUpgrade.pas' {FrmAutoUpgrade},
  View.Query.ContaAReceber in '..\Sys\View\Query\View.Query.ContaAReceber.pas' {ViewQueryContaAReceber},
  UGeResultadoExercicioImpressao in '..\Sys\UGeResultadoExercicioImpressao.pas' {frmGeResultadoExercicioImpressao},
  UGeContasAPagarAReceberImpressao in 'UGeContasAPagarAReceberImpressao.pas' {frmGeContasAPagarAReceberImpressao},
  Interacao.Empresa in '..\Sys\Model\Interacao\Interacao.Empresa.pas',
  Interacao.Factory in '..\Sys\Model\Interacao\Interacao.Factory.pas',
  Interacao.Funcao in '..\Sys\Model\Interacao\Interacao.Funcao.pas',
  Interacao.Licenca in '..\Sys\Model\Interacao\Interacao.Licenca.pas',
  Interacao.PersonalizaEmpresa in '..\Sys\Model\Interacao\Interacao.PersonalizaEmpresa.pas',
  Interacao.Pessoa in '..\Sys\Model\Interacao\Interacao.Pessoa.pas',
  Interacao.Usuario in '..\Sys\Model\Interacao\Interacao.Usuario.pas',
  Interacao.Versao in '..\Sys\Model\Interacao\Interacao.Versao.pas',
  Controller.Empresa in '..\Sys\Controller\Controller.Empresa.pas',
  Controller.Factory in '..\Sys\Controller\Controller.Factory.pas',
  Controller.Licenca in '..\Sys\Controller\Controller.Licenca.pas',
  Controller.PersonalizaEmpresa in '..\Sys\Controller\Controller.PersonalizaEmpresa.pas',
  Controller.Usuario in '..\Sys\Controller\Controller.Usuario.pas',
  Controller.Versao in '..\Sys\Controller\Controller.Versao.pas',
  Classe.Empresa in '..\Sys\Classe\Classe.Empresa.pas',
  Classe.Funcao in '..\Sys\Classe\Classe.Funcao.pas',
  Classe.Licenca in '..\Sys\Classe\Classe.Licenca.pas',
  Classe.Pessoa in '..\Sys\Classe\Classe.Pessoa.pas',
  Classe.PessoaFisica in '..\Sys\Classe\Classe.PessoaFisica.pas',
  Classe.PessoaJuridica in '..\Sys\Classe\Classe.PessoaJuridica.pas',
  Classe.Usuario in '..\Sys\Classe\Classe.Usuario.pas',
  View.PadraoLogin in '..\Sys\View\View.PadraoLogin.pas' {FrmPadraoLogin},
  View.PadraoCadastro in '..\Sys\View\View.PadraoCadastro.pas' {ViewPadraoCadastro},
  View.PadraoPesquisa in '..\Sys\View\View.PadraoPesquisa.pas' {ViewPadraoPesquisa},
  View.Login in 'View\View.Login.pas' {FrmLogin},
  View.InputQuery in '..\Sys\Services\InputQuery\View.InputQuery.pas' {ViewInputQuery},
  View.Esmaecer in '..\Sys\View\View.Esmaecer.pas' {ViewEsmaecer},
  View.VendaMobile in 'View\View.VendaMobile.pas' {ViewVendaMobile},
  View.VendaMobile.Configurar in 'View\View.VendaMobile.Configurar.pas' {ViewVendaMobileConfigurar},
  View.VendaMobile.Configurar.Chave in 'View\View.VendaMobile.Configurar.Chave.pas' {ViewVendaMobileConfigurarChave},
  Frame.VendaMobile.Menu in 'View\Components\Frame.VendaMobile.Menu.pas' {FrameVendaMobileMenu: TFrame},
  Frame.VendaMobile.Configurar.Menu in 'View\Components\Frame.VendaMobile.Configurar.Menu.pas' {FrameVendaMobileConfigurarMenu: TFrame},
  Service.InputQuery in '..\Sys\Services\Service.InputQuery.pas',
  Service.Utils in '..\Sys\Services\Service.Utils.pas',
  Service.PrevisaoTempo in '..\Sys\Services\Service.PrevisaoTempo.pas',
  Service.Message in '..\Sys\Services\Service.Message.pas',
  Service.Encript in '..\Sys\Services\Service.Encript.pas',
  Service.Format.VCL in '..\Sys\Services\Service.Format.VCL.pas',
  Service.Request in '..\Sys\Services\Service.Request.pas',
  Service.Request.CEP in '..\Sys\Services\Service.Request.CEP.pas',
  Service.Request.CNPJ in '..\Sys\Services\Service.Request.CNPJ.pas',
  Interacao.Tabela in '..\Sys\Model\Interacao\Interacao.Tabela.pas',
  Controller.Tabela in '..\Sys\Controller\Controller.Tabela.pas',
  Interfaces.InputQuery in '..\Sys\Services\InputQuery\Interfaces.InputQuery.pas',
  Classe.DistribuicaoDFe.DocumentoRetornado in '..\Sys\Classe\Classe.DistribuicaoDFe.DocumentoRetornado.pas',
  Interfaces.PrevisaoTempo in '..\Sys\Services\PrevisaoTempo\Interfaces.PrevisaoTempo.pas',
  Controller.ProvisaoTempo.Inpe in '..\Sys\Services\PrevisaoTempo\Controller.ProvisaoTempo.Inpe.pas',
  Controller.ProvisaoTempo.WeatherstackAPI in '..\Sys\Services\PrevisaoTempo\Controller.ProvisaoTempo.WeatherstackAPI.pas',
  View.VendaMobile.Vendedor in 'View\View.VendaMobile.Vendedor.pas' {ViewVendaMobileVendedor},
  Classe.Gerenciador.View in '..\Sys\Classe\Classe.Gerenciador.View.pas',
  Interacao.Gerenciador.View in '..\Sys\Classe\Interacao\Interacao.Gerenciador.View.pas',
  Controller.ProvisaoTempo.OpenWeatherMapAPI in '..\Sys\Services\PrevisaoTempo\Controller.ProvisaoTempo.OpenWeatherMapAPI.pas',
  Controller.ProvisaoTempo.HGWeatherAPI in '..\Sys\Services\PrevisaoTempo\Controller.ProvisaoTempo.HGWeatherAPI.pas',
  SGE.Model.Dados in '..\Sys\Model\SGE.Model.Dados.pas' {DMDados: TDataModule},
  SGE.Model.Conexao.DataSet in '..\Sys\Model\Conexao\SGE.Model.Conexao.DataSet.pas' {ModelConexaoDataSet: TDataModule},
  SGE.Model.Factory in '..\Sys\Model\SGE.Model.Factory.pas',
  SGE.Controller.Estado.OLD in '..\Sys\Controller\SGE.Controller.Estado.OLD.pas',
  SGE.Model.Interacao.DataSet in '..\Sys\Model\Interacao\SGE.Model.Interacao.DataSet.pas',
  Model.Conexao.Interfaces in '..\Sys\Model\Conexao\Model.Conexao.Interfaces.pas',
  Model.Conexao.Firedac in '..\Sys\Model\Conexao\Model.Conexao.Firedac.pas',
  Model.Conexao.Firedac.Firebird in '..\Sys\Model\Conexao\Model.Conexao.Firedac.Firebird.pas',
  Model.Conexao.Factory.Interfaces in '..\Sys\Model\Conexao\Model.Conexao.Factory.Interfaces.pas',
  Model.Conexao.Factory in '..\Sys\Model\Conexao\Model.Conexao.Factory.pas',
  Model.Query.Interfaces in '..\Sys\Model\Conexao\Model.Query.Interfaces.pas',
  Model.Query.Firedac in '..\Sys\Model\Conexao\Model.Query.Firedac.pas',
  Model.Constantes in '..\Sys\Model\Model.Constantes.pas',
  Model.Entidade.ConfiguracaoAPI in '..\Sys\Model\Entidade\Model.Entidade.ConfiguracaoAPI.pas',
  Model.Entidade.ConfiguracaoINI in '..\Sys\Model\Entidade\Model.Entidade.ConfiguracaoINI.pas',
  SGE.Model.Connection.Component.SQL in '..\Sys\Model\Connection\Component\SGE.Model.Connection.Component.SQL.pas',
  SGE.Model.Connection.Interfaces in '..\Sys\Model\Connection\SGE.Model.Connection.Interfaces.pas',
  SGE.Model.Connection.FireDAC in '..\Sys\Model\Connection\SGE.Model.Connection.FireDAC.pas',
  SGE.Model.Connection.Factory in '..\Sys\Model\Connection\SGE.Model.Connection.Factory.pas',
  SGE.Model.DAO.Interfaces in '..\Sys\Model\DAO\SGE.Model.DAO.Interfaces.pas',
  SGE.Model.DAO in '..\Sys\Model\DAO\SGE.Model.DAO.pas',
  SGE.Model.DAO.AutorizacaoCompra in 'Model\DAO\SGE.Model.DAO.AutorizacaoCompra.pas',
  SGE.Model.DAO.Bairro in '..\Sys\Model\DAO\SGE.Model.DAO.Bairro.pas',
  SGE.Model.DAO.Banco in '..\Sys\Model\DAO\SGE.Model.DAO.Banco.pas',
  SGE.Model.DAO.Busca in '..\Sys\Model\DAO\SGE.Model.DAO.Busca.pas',
  SGE.Model.DAO.Caixa in '..\Sys\Model\DAO\SGE.Model.DAO.Caixa.pas',
  SGE.Model.DAO.CentroCusto in '..\Sys\Model\DAO\SGE.Model.DAO.CentroCusto.pas',
  SGE.Model.DAO.CFOP in '..\Sys\Model\DAO\SGE.Model.DAO.CFOP.pas',
  SGE.Model.DAO.Cheque in '..\Sys\Model\DAO\SGE.Model.DAO.Cheque.pas',
  SGE.Model.DAO.Cidade in '..\Sys\Model\DAO\SGE.Model.DAO.Cidade.pas',
  SGE.Model.DAO.Cliente in '..\Sys\Model\DAO\SGE.Model.DAO.Cliente.pas',
  SGE.Model.DAO.CondicaoPagto in '..\Sys\Model\DAO\SGE.Model.DAO.CondicaoPagto.pas',
  SGE.Model.DAO.Config in '..\Sys\Model\DAO\SGE.Model.DAO.Config.pas',
  SGE.Model.DAO.ContaAPagar in '..\Sys\Model\DAO\SGE.Model.DAO.ContaAPagar.pas',
  SGE.Model.DAO.ContaAReceber in '..\Sys\Model\DAO\SGE.Model.DAO.ContaAReceber.pas',
  SGE.Model.DAO.ContaCorrente in '..\Sys\Model\DAO\SGE.Model.DAO.ContaCorrente.pas',
  SGE.Model.DAO.Contrato in '..\Sys\Model\DAO\SGE.Model.DAO.Contrato.pas',
  SGI.Model.DAO.CotacaoCompra in '..\System_SGI\Model\DAO\SGI.Model.DAO.CotacaoCompra.pas',
  SGE.Model.DAO.CST in '..\Sys\Model\DAO\SGE.Model.DAO.CST.pas',
  SGE.Model.DAO.Distrito in '..\Sys\Model\DAO\SGE.Model.DAO.Distrito.pas',
  SGE.Model.DAO.Empresa in '..\Sys\Model\DAO\SGE.Model.DAO.Empresa.pas',
  SGE.Model.DAO.Entrada in '..\Sys\Model\DAO\SGE.Model.DAO.Entrada.pas',
  SGE.Model.DAO.Estado in '..\Sys\Model\DAO\SGE.Model.DAO.Estado.pas',
  SGE.Model.DAO.Factory in '..\Sys\Model\DAO\SGE.Model.DAO.Factory.pas',
  SGE.Model.DAO.FormaPagto in '..\Sys\Model\DAO\SGE.Model.DAO.FormaPagto.pas',
  SGE.Model.DAO.Fornecedor in '..\Sys\Model\DAO\SGE.Model.DAO.Fornecedor.pas',
  SGE.Model.DAO.Helper in '..\Sys\Model\DAO\SGE.Model.DAO.Helper.pas',
  SGE.Model.DAO.IBPT in '..\Sys\Model\DAO\SGE.Model.DAO.IBPT.pas',
  SGE.Model.DAO.Licenca in '..\Sys\Model\DAO\SGE.Model.DAO.Licenca.pas',
  SGE.Model.DAO.Logradouro in '..\Sys\Model\DAO\SGE.Model.DAO.Logradouro.pas',
  SGE.Model.DAO.LogTransacao in '..\Sys\Model\DAO\SGE.Model.DAO.LogTransacao.pas',
  SGE.Model.DAO.Perfil in '..\Sys\Model\DAO\SGE.Model.DAO.Perfil.pas',
  SGE.Model.DAO.PlanoConta in '..\Sys\Model\DAO\SGE.Model.DAO.PlanoConta.pas',
  SGE.Model.DAO.Produto in '..\Sys\Model\DAO\SGE.Model.DAO.Produto.pas',
  SGE.Model.DAO.Promocao in 'Model\DAO\SGE.Model.DAO.Promocao.pas',
  SGE.Model.DAO.RequisicaoCompra in 'Model\DAO\SGE.Model.DAO.RequisicaoCompra.pas',
  SGE.Model.DAO.Rotina in '..\Sys\Model\DAO\SGE.Model.DAO.Rotina.pas',
  SGI.Model.DAO.SolicitacaoCompra in '..\System_SGI\Model\DAO\SGI.Model.DAO.SolicitacaoCompra.pas',
  SGE.Model.DAO.Tabelas in '..\Sys\Model\DAO\SGE.Model.DAO.Tabelas.pas',
  SGE.Model.DAO.TipoDespesa in '..\Sys\Model\DAO\SGE.Model.DAO.TipoDespesa.pas',
  SGE.Model.DAO.TipoLogradouro in '..\Sys\Model\DAO\SGE.Model.DAO.TipoLogradouro.pas',
  SGE.Model.DAO.TipoReceita in '..\Sys\Model\DAO\SGE.Model.DAO.TipoReceita.pas',
  SGE.Model.DAO.UF in '..\Sys\Model\DAO\SGE.Model.DAO.UF.pas',
  SGE.Model.DAO.Usuario in '..\Sys\Model\DAO\SGE.Model.DAO.Usuario.pas',
  SGE.Model.DAO.Vendedor in '..\Sys\Model\DAO\SGE.Model.DAO.Vendedor.pas',
  SGE.Model.DAO.XML_NFeEnviada in 'Model\DAO\SGE.Model.DAO.XML_NFeEnviada.pas',
  SGE.Model.DAO.XML_NFeImportada in 'Model\DAO\SGE.Model.DAO.XML_NFeImportada.pas',
  SGI.Model.DAO.ProdutoAlmoxarifado in '..\System_SGI\Model\DAO\SGI.Model.DAO.ProdutoAlmoxarifado.pas',
  SGI.Model.DAO.RequisicaoAlmoxarifado in '..\System_SGI\Model\DAO\SGI.Model.DAO.RequisicaoAlmoxarifado.pas',
  SGE.Model.DAO.Query.Interfaces in '..\Sys\Model\DAO\Query\SGE.Model.DAO.Query.Interfaces.pas',
  SGE.Model.DAO.Query.Factory in '..\Sys\Model\DAO\Query\SGE.Model.DAO.Query.Factory.pas',
  SGI.Model.DAO.Query.ApropriacaoEstoque in '..\System_SGI\Model\DAO\Query\SGI.Model.DAO.Query.ApropriacaoEstoque.pas',
  SGE.Model.DAO.Query.Caixa in '..\Sys\Model\DAO\Query\SGE.Model.DAO.Query.Caixa.pas',
  SGE.Model.DAO.Query.ContaAPagar in '..\Sys\Model\DAO\Query\SGE.Model.DAO.Query.ContaAPagar.pas',
  SGE.Model.DAO.Query.ContaAReceber in '..\Sys\Model\DAO\Query\SGE.Model.DAO.Query.ContaAReceber.pas',
  SGE.Model.DAO.Query.FornecedorCliente in '..\Sys\Model\DAO\Query\SGE.Model.DAO.Query.FornecedorCliente.pas',
  SGE.Controller.Interfaces in '..\Sys\Controller\SGE.Controller.Interfaces.pas',
  SGE.Controller in '..\Sys\Controller\SGE.Controller.pas',
  SGE.Controller.AutorizacaoCompra in 'Controller\SGE.Controller.AutorizacaoCompra.pas',
  SGE.Controller.Bairro in '..\Sys\Controller\SGE.Controller.Bairro.pas',
  SGE.Controller.Banco in '..\Sys\Controller\SGE.Controller.Banco.pas',
  SGE.Controller.Caixa in '..\Sys\Controller\SGE.Controller.Caixa.pas',
  SGE.Controller.CentroCusto in '..\Sys\Controller\SGE.Controller.CentroCusto.pas',
  SGE.Controller.CFOP in '..\Sys\Controller\SGE.Controller.CFOP.pas',
  SGE.Controller.Cheque in '..\Sys\Controller\SGE.Controller.Cheque.pas',
  SGE.Controller.Cidade in '..\Sys\Controller\SGE.Controller.Cidade.pas',
  SGE.Controller.Cliente in '..\Sys\Controller\SGE.Controller.Cliente.pas',
  SGE.Controller.CondicaoPagto in '..\Sys\Controller\SGE.Controller.CondicaoPagto.pas',
  SGE.Controller.Config in '..\Sys\Controller\SGE.Controller.Config.pas',
  SGE.Controller.ContaAPagar in '..\Sys\Controller\SGE.Controller.ContaAPagar.pas',
  SGE.Controller.ContaAReceber in '..\Sys\Controller\SGE.Controller.ContaAReceber.pas',
  SGE.Controller.ContaCorrente in '..\Sys\Controller\SGE.Controller.ContaCorrente.pas',
  SGE.Controller.Contrato in '..\Sys\Controller\SGE.Controller.Contrato.pas',
  SGI.Controller.CotacaoCompra in '..\System_SGI\Controller\SGI.Controller.CotacaoCompra.pas',
  SGE.Controller.CST in '..\Sys\Controller\SGE.Controller.CST.pas',
  SGE.Controller.Distrito in '..\Sys\Controller\SGE.Controller.Distrito.pas',
  SGE.Controller.Empresa in '..\Sys\Controller\SGE.Controller.Empresa.pas',
  SGE.Controller.Endereco in '..\Sys\Controller\SGE.Controller.Endereco.pas',
  SGE.Controller.Entrada in '..\Sys\Controller\SGE.Controller.Entrada.pas',
  SGE.Controller.Estado in '..\Sys\Controller\SGE.Controller.Estado.pas',
  SGE.Controller.Factory in '..\Sys\Controller\SGE.Controller.Factory.pas',
  SGE.Controller.FormaPagto in '..\Sys\Controller\SGE.Controller.FormaPagto.pas',
  SGE.Controller.Fornecedor in '..\Sys\Controller\SGE.Controller.Fornecedor.pas',
  SGE.Controller.Helper in '..\Sys\Controller\SGE.Controller.Helper.pas',
  SGE.Controller.IBPT in '..\Sys\Controller\SGE.Controller.IBPT.pas',
  SGE.Controller.Logradouro in '..\Sys\Controller\SGE.Controller.Logradouro.pas',
  SGE.Controller.LogTransacao in '..\Sys\Controller\SGE.Controller.LogTransacao.pas',
  SGE.Controller.Perfil in '..\Sys\Controller\SGE.Controller.Perfil.pas',
  SGE.Controller.PlanoConta in '..\Sys\Controller\SGE.Controller.PlanoConta.pas',
  SGE.Controller.Produto in '..\Sys\Controller\SGE.Controller.Produto.pas',
  SGE.Controller.Promocao in 'Controller\SGE.Controller.Promocao.pas',
  SGE.Controller.RequisicaoCompra in 'Controller\SGE.Controller.RequisicaoCompra.pas',
  SGE.Controller.Rotina in '..\Sys\Controller\SGE.Controller.Rotina.pas',
  SGI.Controller.SolicitacaoCompra in '..\System_SGI\Controller\SGI.Controller.SolicitacaoCompra.pas',
  SGE.Controller.Tabelas in '..\Sys\Controller\SGE.Controller.Tabelas.pas',
  SGE.Controller.TipoDespesa in '..\Sys\Controller\SGE.Controller.TipoDespesa.pas',
  SGE.Controller.TipoLogradouro in '..\Sys\Controller\SGE.Controller.TipoLogradouro.pas',
  SGE.Controller.TipoReceita in '..\Sys\Controller\SGE.Controller.TipoReceita.pas',
  SGE.Controller.UF in '..\Sys\Controller\SGE.Controller.UF.pas',
  SGE.Controller.Usuario in '..\Sys\Controller\SGE.Controller.Usuario.pas',
  SGE.Controller.Vendedor in '..\Sys\Controller\SGE.Controller.Vendedor.pas',
  SGE.Controller.XML_NFeEnviada in 'Controller\SGE.Controller.XML_NFeEnviada.pas',
  SGE.Controller.XML_NFeImportada in 'Controller\SGE.Controller.XML_NFeImportada.pas',
  SGE.Controller.Query in '..\Sys\Controller\Query\SGE.Controller.Query.pas',
  SGE.Controller.Query.Interfaces in '..\Sys\Controller\Query\SGE.Controller.Query.Interfaces.pas',
  SGE.Controller.Query.Factory in '..\Sys\Controller\Query\SGE.Controller.Query.Factory.pas',
  SGE.Controller.Query.ContaAPagar in '..\Sys\Controller\Query\SGE.Controller.Query.ContaAPagar.pas',
  SGE.Controller.Query.ContaAReceber in '..\Sys\Controller\Query\SGE.Controller.Query.ContaAReceber.pas',
  SGE.Controller.Query.FornecedorCliente in '..\Sys\Controller\Query\SGE.Controller.Query.FornecedorCliente.pas',
  SGE.Controller.Impressao.DataModule.AutorizacaoCompra in '..\Sys\Controller\Impressao\DataModule\SGE.Controller.Impressao.DataModule.AutorizacaoCompra.pas' {DataModuleAutorizacaoCompra: TDataModule},
  SGE.Controller.Impressao.DataModule.ContaAPagar in '..\Sys\Controller\Impressao\DataModule\SGE.Controller.Impressao.DataModule.ContaAPagar.pas' {DataModuleContaAPagar: TDataModule},
  SGE.Controller.Impressao.DataModule.ContaAReceber in '..\Sys\Controller\Impressao\DataModule\SGE.Controller.Impressao.DataModule.ContaAReceber.pas' {DataModuleContaAReceber: TDataModule},
  SGE.Controller.Impressao.DataModule.Contrato in '..\Sys\Controller\Impressao\DataModule\SGE.Controller.Impressao.DataModule.Contrato.pas' {DataModuleContrato: TDataModule},
  SGI.Controller.Impressao.DataModule.CotacaoCompra in '..\System_SGI\Controller\Impressao\DataModule\SGI.Controller.Impressao.DataModule.CotacaoCompra.pas' {DataModuleCotacaoCompra: TDataModule},
  SGE.Controller.Impressao.DataModule.Cheque in '..\Sys\Controller\Impressao\DataModule\SGE.Controller.Impressao.DataModule.Cheque.pas' {DataModuleCheque: TDataModule},
  SGI.Controller.Impressao.DataModule.SolicitacaoCompra in '..\System_SGI\Controller\Impressao\DataModule\SGI.Controller.Impressao.DataModule.SolicitacaoCompra.pas' {DataModuleSolicitacaoCompra: TDataModule},
  SGE.Controller.Impressao.AutorizacaoCompra in '..\Sys\Controller\Impressao\SGE.Controller.Impressao.AutorizacaoCompra.pas',
  SGE.Controller.Impressao.ContaAPagar in '..\Sys\Controller\Impressao\SGE.Controller.Impressao.ContaAPagar.pas',
  SGE.Controller.Impressao.ContaAReceber in '..\Sys\Controller\Impressao\SGE.Controller.Impressao.ContaAReceber.pas',
  SGE.Controller.Impressao.Contrato in '..\Sys\Controller\Impressao\SGE.Controller.Impressao.Contrato.pas',
  SGI.Controller.Impressao.CotacaoCompra in '..\System_SGI\Controller\Impressao\SGI.Controller.Impressao.CotacaoCompra.pas',
  SGE.Controller.Impressao.Cheque in '..\Sys\Controller\Impressao\SGE.Controller.Impressao.Cheque.pas',
  SGI.Controller.Impressao.SolicitacaoCompra in '..\System_SGI\Controller\Impressao\SGI.Controller.Impressao.SolicitacaoCompra.pas',
  SGI.Controller.ProdutoAlmoxarifado in '..\System_SGI\Controller\SGI.Controller.ProdutoAlmoxarifado.pas',
  SGI.Controller.RequisicaoAlmoxarifado in '..\System_SGI\Controller\SGI.Controller.RequisicaoAlmoxarifado.pas',
  SGI.Controller.Query.ApropriacaoEstoque in '..\System_SGI\Controller\Query\SGI.Controller.Query.ApropriacaoEstoque.pas',
  SGE.Controller.Query.Caixa in '..\Sys\Controller\Query\SGE.Controller.Query.Caixa.pas',
  View.CampoRequisitado in '..\Sys\View\View.CampoRequisitado.pas' {ViewCampoRequisitado},
  View.Estado in '..\Sys\View\View.Estado.pas' {ViewEstado},
  View.Cidade in '..\Sys\View\View.Cidade.pas' {ViewCidade},
  View.Distrito in '..\Sys\View\View.Distrito.pas' {ViewDistrito},
  View.Bairro in '..\Sys\View\View.Bairro.pas' {ViewBairro},
  View.TipoLogradouro in '..\Sys\View\View.TipoLogradouro.pas' {ViewTipoLogradouro},
  View.Logradouro in '..\Sys\View\View.Logradouro.pas' {ViewLogradouro},
  View.CFOP in '..\Sys\View\View.CFOP.pas' {ViewCFOP},
  View.IBPT in '..\Sys\View\View.IBPT.pas' {ViewIBPT},
  View.IBPT.Importar in '..\Sys\View\View.IBPT.Importar.pas' {ViewIBPTImportar},
  View.ContaCorrente in '..\Sys\View\View.ContaCorrente.pas' {ViewContaCorrente},
  View.FormaPagto in '..\Sys\View\View.FormaPagto.pas' {ViewFormaPagto},
  View.CondicaoPagto in '..\Sys\View\View.CondicaoPagto.pas' {ViewCondicaoPagto},
  View.PlanoConta in '..\Sys\View\View.PlanoConta.pas' {ViewPlanoConta},
  View.TipoReceita in '..\Sys\View\View.TipoReceita.pas' {ViewTipoReceita},
  View.TipoDespesa in '..\Sys\View\View.TipoDespesa.pas' {ViewTipoDespesa},
  View.CentroCusto in '..\Sys\View\View.CentroCusto.pas' {ViewCentroCusto},
  View.Empresa in '..\Sys\View\View.Empresa.pas' {ViewEmpresa},
  View.ConfiguracaoEmpresa in '..\Sys\View\View.ConfiguracaoEmpresa.pas' {ViewConfiguracaoEmpresa},
  View.Vendedor in '..\Sys\View\View.Vendedor.pas' {ViewVendedor},
  View.Cliente in '..\Sys\View\View.Cliente.pas' {ViewCliente},
  View.Fornecedor in '..\Sys\View\View.Fornecedor.pas' {ViewFornecedor},
  View.Banco in '..\Sys\View\View.Banco.pas' {ViewBanco},
  View.GrupoProduto in '..\Sys\View\View.GrupoProduto.pas' {ViewGrupoProduto},
  View.SecaoProduto in '..\Sys\View\View.SecaoProduto.pas' {ViewSecaoProduto},
  View.FabricanteProduto in '..\Sys\View\View.FabricanteProduto.pas' {ViewFabricanteProduto},
  View.UnidadeProduto in '..\Sys\View\View.UnidadeProduto.pas' {ViewUnidadeProduto},
  View.Produto in '..\Sys\View\View.Produto.pas' {ViewProduto},
  View.Certificado in '..\Sys\View\View.Certificado.pas' {ViewCertificado},
  View.Promocao in 'View\View.Promocao.pas' {ViewPromocao},
  View.Cheque in '..\Sys\View\View.Cheque.pas' {ViewCheque},
  View.AutorizacaoCompra in 'View\View.AutorizacaoCompra.pas' {ViewAutorizacaoCompra},
  View.AutorizacaoCompra.Cancelar in 'View\View.AutorizacaoCompra.Cancelar.pas' {ViewAutorizacaoCompraCancelar},
  View.RequisicaoCompra in 'View\View.RequisicaoCompra.pas' {ViewRequisicaoCompra},
  View.RequisicaoCompra.Cancelar in 'View\View.RequisicaoCompra.Cancelar.pas' {ViewRequisicaoCompraCancelar},
  View.Entrada in '..\Sys\View\View.Entrada.pas' {ViewEntrada},
  View.Entrada.ConfirmarDuplicatas in '..\Sys\View\View.Entrada.ConfirmarDuplicatas.pas' {ViewEntradaConfirmarDuplicatas},
  View.Entrada.ConfirmarLote in '..\Sys\View\View.Entrada.ConfirmarLote.pas' {ViewEntradaEstoqueLote},
  View.Entrada.Cancelar in '..\Sys\View\View.Entrada.Cancelar.pas' {ViewEntradaEstoqueCancelar},
  View.Entrada.GerarNFE in '..\Sys\View\View.Entrada.GerarNFE.pas' {ViewEntradaEstoqueGerarNFE},
  View.Entrada.DevolucaoNF in '..\Sys\View\View.Entrada.DevolucaoNF.pas' {ViewEntradaDevolucaoNF},
  View.NFE.ConsultarLote in '..\Sys\View\View.NFE.ConsultarLote.pas' {ViewNFEConsultarLote},
  View.NFE.Pesquisa in '..\Sys\View\View.NFE.Pesquisa.pas' {ViewNFEPesquisa},
  View.NFE.Distribuicao in '..\Sys\View\View.NFE.Distribuicao.pas' {ViewNFEDistribuicao},
  View.NFE.Importar in '..\Sys\View\View.NFE.Importar.pas' {ViewNFEImportar},
  View.ContaAPagar in '..\Sys\View\View.ContaAPagar.pas' {ViewContaAPagar},
  View.WaitAMoment in '..\Sys\View\View.WaitAMoment.pas' {ViewWaitAMoment},
  View.ContaAPagar.LoteParcela in '..\Sys\View\View.ContaAPagar.LoteParcela.pas' {ViewContaAPagarLoteParcela},
  View.ContaAPagar.Pagamento in '..\Sys\View\View.ContaAPagar.Pagamento.pas' {ViewContaAPagarPagamento},
  View.Query.FornecedorCliente in '..\Sys\View\Query\View.Query.FornecedorCliente.pas' {ViewQueryFornecedorCliente},
  View.Query.ContaAPagar in '..\Sys\View\Query\View.Query.ContaAPagar.pas' {ViewQueryContaAPagar},
  View.ContaAReceber in '..\Sys\View\View.ContaAReceber.pas' {ViewContaAReceber},
  View.ContaAReceber.LoteParcela in '..\Sys\View\View.ContaAReceber.LoteParcela.pas' {ViewContaAReceberLoteParcela},
  View.ContaAReceber.Pagamento in '..\Sys\View\View.ContaAReceber.Pagamento.pas' {ViewContaAReceberPagamento},
  View.Usuario in '..\Sys\View\View.Usuario.pas' {ViewUsuario},
  View.Usuario.AlterarSenha in '..\Sys\View\View.Usuario.AlterarSenha.pas' {ViewUsuarioAlterarSenha},
  View.Contrato in '..\Sys\View\View.Contrato.pas' {ViewContrato},
  View.Query.Caixa.Conferencia in '..\Sys\View\Query\View.Query.Caixa.Conferencia.pas' {ViewQueryCaixaConferencia},
  View.Servico.ConsultarCNPJ in '..\Sys\View\View.Servico.ConsultarCNPJ.pas' {ViewServicoConsultarCNPJ},
  View.Perfil in '..\Sys\View\View.Perfil.pas' {ViewPerfil},
  View.Perfil.Copiar in '..\Sys\View\View.Perfil.Copiar.pas' {ViewPerfilCopiar},
  View.CotacaoCompra.Cancelar in '..\System_SGI\View\View.CotacaoCompra.Cancelar.pas' {ViewCotacaoCompraCancelar},
  View.CotacaoCompra.Fornecedor in '..\System_SGI\View\View.CotacaoCompra.Fornecedor.pas' {ViewCotacaoCompraFornecedor},
  View.CotacaoCompra in '..\System_SGI\View\View.CotacaoCompra.pas' {ViewCotacaoCompra};

{$R *.res}

begin
  FileINI := TIniFile.Create( ExtractFilePath(ParamStr(0)) + 'Conexao.ini' );

  Application.Initialize;
  Application.Title := 'SGE | Sistema Integrado de Gestão Empresarial/Comercial';

  SplashShow(Application);

  Application.CreateForm(TDMRecursos, DMRecursos);
  Application.CreateForm(TDMBusiness, DMBusiness);
  Application.CreateForm(TDMNFe, DMNFe);
  Application.CreateForm(TDataModuleCotacaoCompra, DataModuleCotacaoCompra);
  Application.CreateForm(TDataModuleSolicitacaoCompra, DataModuleSolicitacaoCompra);
  SplashFree;

  if ExecutarLogin() then
    Application.CreateForm(TfrmPrinc, frmPrinc);

  Application.Run;
end.
