program SGE_PDV;

uses
  Windows,
  Forms,
  Controls,
  IniFiles,
  SysUtils,
  MidasLIB,
  HPL_Strings in '..\Sys\lib\HPL_Strings.pas',
  FormFactoryU in '..\Sys\lib\FormFactoryU.pas',
  FuncoesFormulario in '..\Sys\lib\FuncoesFormulario.pas',
  UConstantesDGE in '..\Sys\UConstantesDGE.pas',
  Service.Encript in '..\Sys\Services\Service.Encript.pas',
  Service.Format.VCL in '..\Sys\Services\Service.Format.VCL.pas',
  Service.InputQuery in '..\Sys\Services\Service.InputQuery.pas',
  Service.Message in '..\Sys\Services\Service.Message.pas',
  Service.Request.CEP in '..\Sys\Services\Service.Request.CEP.pas',
  Service.Request.CNPJ in '..\Sys\Services\Service.Request.CNPJ.pas',
  Service.Request in '..\Sys\Services\Service.Request.pas',
  Service.Utils in '..\Sys\Services\Service.Utils.pas',
  Model.Licenca in '..\GerarLicenca\Model\Model.Licenca.pas',
  Model.Usuario in '..\GerarLicenca\Model\Model.Usuario.pas',
  Model.Endereco in '..\GerarLicenca\Model\Model.Endereco.pas',
  Model.Cliente in '..\GerarLicenca\Model\Model.Cliente.pas',
  Controller.Interfaces in '..\GerarLicenca\Controller\Controller.Interfaces.pas',
  Controller.UsuarioApp in '..\GerarLicenca\Controller\Controller.UsuarioApp.pas',
  Controller.ClienteApp in '..\GerarLicenca\Controller\Controller.ClienteApp.pas',
  Controller.FactoryApp in '..\GerarLicenca\Controller\Controller.FactoryApp.pas',
  Interacao.Conexao in '..\Sys\Model\Interacao\Interacao.Conexao.pas',
  Interacao.Empresa in '..\Sys\Model\Interacao\Interacao.Empresa.pas',
  Interacao.Factory in '..\Sys\Model\Interacao\Interacao.Factory.pas',
  Interacao.Funcao in '..\Sys\Model\Interacao\Interacao.Funcao.pas',
  Interacao.Licenca in '..\Sys\Model\Interacao\Interacao.Licenca.pas',
  Interacao.PersonalizaEmpresa in '..\Sys\Model\Interacao\Interacao.PersonalizaEmpresa.pas',
  Interacao.Pessoa in '..\Sys\Model\Interacao\Interacao.Pessoa.pas',
  Interacao.Tabela in '..\Sys\Model\Interacao\Interacao.Tabela.pas',
  Interacao.Usuario in '..\Sys\Model\Interacao\Interacao.Usuario.pas',
  Interacao.Versao in '..\Sys\Model\Interacao\Interacao.Versao.pas',
  Interfaces.InputQuery in '..\Sys\Services\InputQuery\Interfaces.InputQuery.pas',
  Controller.Empresa in '..\Sys\Controller\Controller.Empresa.pas',
  Controller.Factory in '..\Sys\Controller\Controller.Factory.pas',
  Controller.Licenca in '..\Sys\Controller\Controller.Licenca.pas',
  Controller.PersonalizaEmpresa in '..\Sys\Controller\Controller.PersonalizaEmpresa.pas',
  Controller.Tabela in '..\Sys\Controller\Controller.Tabela.pas',
  Controller.Usuario in '..\Sys\Controller\Controller.Usuario.pas',
  Controller.Versao in '..\Sys\Controller\Controller.Versao.pas',
  Classe.Conexao in '..\Sys\Classe\Classe.Conexao.pas',
  Classe.Empresa in '..\Sys\Classe\Classe.Empresa.pas',
  Classe.Funcao in '..\Sys\Classe\Classe.Funcao.pas',
  Classe.Licenca in '..\Sys\Classe\Classe.Licenca.pas',
  Classe.Pessoa in '..\Sys\Classe\Classe.Pessoa.pas',
  Classe.PessoaFisica in '..\Sys\Classe\Classe.PessoaFisica.pas',
  Classe.PessoaJuridica in '..\Sys\Classe\Classe.PessoaJuridica.pas',
  Classe.Usuario in '..\Sys\Classe\Classe.Usuario.pas',
  SGE.Model.Connection.Component.SQL in '..\Sys\Model\Connection\Component\SGE.Model.Connection.Component.SQL.pas',
  SGE.Model.Connection.Factory in '..\Sys\Model\Connection\SGE.Model.Connection.Factory.pas',
  SGE.Model.Connection.FireDAC in '..\Sys\Model\Connection\SGE.Model.Connection.FireDAC.pas',
  SGE.Model.Connection.Interfaces in '..\Sys\Model\Connection\SGE.Model.Connection.Interfaces.pas',
  SGE.Model.DAO in '..\Sys\Model\DAO\SGE.Model.DAO.pas',
  SGE.Model.DAO.Interfaces in '..\Sys\Model\DAO\SGE.Model.DAO.Interfaces.pas',
  SGE.Model.DAO.Bairro in '..\Sys\Model\DAO\SGE.Model.DAO.Bairro.pas',
  SGE.Model.DAO.Banco in '..\Sys\Model\DAO\SGE.Model.DAO.Banco.pas',
  SGE.Model.DAO.Busca in '..\Sys\Model\DAO\SGE.Model.DAO.Busca.pas',
  SGE.Model.DAO.Caixa in '..\Sys\Model\DAO\SGE.Model.DAO.Caixa.pas',
  SGE.Model.DAO.CentroCusto in '..\Sys\Model\DAO\SGE.Model.DAO.CentroCusto.pas',
  SGE.Model.DAO.Cheque in '..\Sys\Model\DAO\SGE.Model.DAO.Cheque.pas',
  SGE.Model.DAO.CFOP in '..\Sys\Model\DAO\SGE.Model.DAO.CFOP.pas',
  SGE.Model.DAO.Cidade in '..\Sys\Model\DAO\SGE.Model.DAO.Cidade.pas',
  SGE.Model.DAO.Cliente in '..\Sys\Model\DAO\SGE.Model.DAO.Cliente.pas',
  SGE.Model.DAO.CondicaoPagto in '..\Sys\Model\DAO\SGE.Model.DAO.CondicaoPagto.pas',
  SGE.Model.DAO.Config in '..\Sys\Model\DAO\SGE.Model.DAO.Config.pas',
  SGE.Model.DAO.ContaAPagar in '..\Sys\Model\DAO\SGE.Model.DAO.ContaAPagar.pas',
  SGE.Model.DAO.ContaAReceber in '..\Sys\Model\DAO\SGE.Model.DAO.ContaAReceber.pas',
  SGE.Model.DAO.ContaCorrente in '..\Sys\Model\DAO\SGE.Model.DAO.ContaCorrente.pas',
  SGE.Model.DAO.Contrato in '..\Sys\Model\DAO\SGE.Model.DAO.Contrato.pas',
  SGE.Model.DAO.CST in '..\Sys\Model\DAO\SGE.Model.DAO.CST.pas',
  SGE.Model.DAO.Distrito in '..\Sys\Model\DAO\SGE.Model.DAO.Distrito.pas',
  SGE.Model.DAO.Empresa in '..\Sys\Model\DAO\SGE.Model.DAO.Empresa.pas',
  SGE.Model.DAO.Entrada in '..\Sys\Model\DAO\SGE.Model.DAO.Entrada.pas',
  SGE.Model.DAO.Estado in '..\Sys\Model\DAO\SGE.Model.DAO.Estado.pas',
  SGE.Model.DAO.Factory in '..\Sys\Model\DAO\SGE.Model.DAO.Factory.pas',
  SGE.Model.DAO.FormaPagto in '..\Sys\Model\DAO\SGE.Model.DAO.FormaPagto.pas',
  SGE.Model.DAO.Fornecedor in '..\Sys\Model\DAO\SGE.Model.DAO.Fornecedor.pas',
  SGE.Model.DAO.Helper in '..\Sys\Model\DAO\SGE.Model.DAO.Helper.pas',
  SGE.Model.DAO.IBPT in '..\Sys\Model\DAO\SGE.Model.DAO.IBPT.pas',
  SGE.Model.DAO.Licenca in '..\Sys\Model\DAO\SGE.Model.DAO.Licenca.pas',
  SGE.Model.DAO.Logradouro in '..\Sys\Model\DAO\SGE.Model.DAO.Logradouro.pas',
  SGE.Model.DAO.LogTransacao in '..\Sys\Model\DAO\SGE.Model.DAO.LogTransacao.pas',
  SGE.Model.DAO.Perfil in '..\Sys\Model\DAO\SGE.Model.DAO.Perfil.pas',
  SGE.Model.DAO.PlanoConta in '..\Sys\Model\DAO\SGE.Model.DAO.PlanoConta.pas',
  SGE.Model.DAO.Produto in '..\Sys\Model\DAO\SGE.Model.DAO.Produto.pas',
  SGE.Model.DAO.Promocao in '..\System_SGE\Model\DAO\SGE.Model.DAO.Promocao.pas',
  SGE.Model.DAO.Rotina in '..\Sys\Model\DAO\SGE.Model.DAO.Rotina.pas',
  SGE.Model.DAO.Tabelas in '..\Sys\Model\DAO\SGE.Model.DAO.Tabelas.pas',
  SGE.Model.DAO.TipoDespesa in '..\Sys\Model\DAO\SGE.Model.DAO.TipoDespesa.pas',
  SGE.Model.DAO.TipoLogradouro in '..\Sys\Model\DAO\SGE.Model.DAO.TipoLogradouro.pas',
  SGE.Model.DAO.TipoReceita in '..\Sys\Model\DAO\SGE.Model.DAO.TipoReceita.pas',
  SGE.Model.DAO.UF in '..\Sys\Model\DAO\SGE.Model.DAO.UF.pas',
  SGE.Model.DAO.Usuario in '..\Sys\Model\DAO\SGE.Model.DAO.Usuario.pas',
  SGE.Model.DAO.Vendedor in '..\Sys\Model\DAO\SGE.Model.DAO.Vendedor.pas',
  SGE.Model.DAO.XML_NFeEnviada in '..\System_SGE\Model\DAO\SGE.Model.DAO.XML_NFeEnviada.pas',
  SGE.Model.DAO.XML_NFeImportada in '..\System_SGE\Model\DAO\SGE.Model.DAO.XML_NFeImportada.pas',
  SGE.Controller in '..\Sys\Controller\SGE.Controller.pas',
  SGE.Controller.Interfaces in '..\Sys\Controller\SGE.Controller.Interfaces.pas',
  SGE.Controller.Factory in '..\Sys\Controller\SGE.Controller.Factory.pas',
  SGE.Controller.Bairro in '..\Sys\Controller\SGE.Controller.Bairro.pas',
  SGE.Controller.Banco in '..\Sys\Controller\SGE.Controller.Banco.pas',
  SGE.Controller.Caixa in '..\Sys\Controller\SGE.Controller.Caixa.pas',
  SGE.Controller.CentroCusto in '..\Sys\Controller\SGE.Controller.CentroCusto.pas',
  SGE.Controller.Cheque in '..\Sys\Controller\SGE.Controller.Cheque.pas',
  SGE.Controller.Cidade in '..\Sys\Controller\SGE.Controller.Cidade.pas',
  SGE.Controller.Cliente in '..\Sys\Controller\SGE.Controller.Cliente.pas',
  SGE.Controller.CondicaoPagto in '..\Sys\Controller\SGE.Controller.CondicaoPagto.pas',
  SGE.Controller.Config in '..\Sys\Controller\SGE.Controller.Config.pas',
  SGE.Controller.ContaAPagar in '..\Sys\Controller\SGE.Controller.ContaAPagar.pas',
  SGE.Controller.ContaAReceber in '..\Sys\Controller\SGE.Controller.ContaAReceber.pas',
  SGE.Controller.ContaCorrente in '..\Sys\Controller\SGE.Controller.ContaCorrente.pas',
  SGE.Controller.CST in '..\Sys\Controller\SGE.Controller.CST.pas',
  SGE.Controller.Distrito in '..\Sys\Controller\SGE.Controller.Distrito.pas',
  SGE.Controller.Empresa in '..\Sys\Controller\SGE.Controller.Empresa.pas',
  SGE.Controller.Endereco in '..\Sys\Controller\SGE.Controller.Endereco.pas',
  SGE.Controller.Entrada in '..\Sys\Controller\SGE.Controller.Entrada.pas',
  SGE.Controller.Estado in '..\Sys\Controller\SGE.Controller.Estado.pas',
  SGE.Controller.FormaPagto in '..\Sys\Controller\SGE.Controller.FormaPagto.pas',
  SGE.Controller.Fornecedor in '..\Sys\Controller\SGE.Controller.Fornecedor.pas',
  SGE.Controller.Helper in '..\Sys\Controller\SGE.Controller.Helper.pas',
  SGE.Controller.IBPT in '..\Sys\Controller\SGE.Controller.IBPT.pas',
  SGE.Controller.Logradouro in '..\Sys\Controller\SGE.Controller.Logradouro.pas',
  SGE.Controller.LogTransacao in '..\Sys\Controller\SGE.Controller.LogTransacao.pas',
  SGE.Controller.Perfil in '..\Sys\Controller\SGE.Controller.Perfil.pas',
  SGE.Controller.PlanoConta in '..\Sys\Controller\SGE.Controller.PlanoConta.pas',
  SGE.Controller.Produto in '..\Sys\Controller\SGE.Controller.Produto.pas',
  SGE.Controller.Rotina in '..\Sys\Controller\SGE.Controller.Rotina.pas',
  SGE.Controller.Tabelas in '..\Sys\Controller\SGE.Controller.Tabelas.pas',
  SGE.Controller.TipoDespesa in '..\Sys\Controller\SGE.Controller.TipoDespesa.pas',
  SGE.Controller.TipoReceita in '..\Sys\Controller\SGE.Controller.TipoReceita.pas',
  SGE.Controller.UF in '..\Sys\Controller\SGE.Controller.UF.pas',
  SGE.Controller.Usuario in '..\Sys\Controller\SGE.Controller.Usuario.pas',
  SGE.Controller.Vendedor in '..\Sys\Controller\SGE.Controller.Vendedor.pas',
  SGE.Controller.TipoLogradouro in '..\Sys\Controller\SGE.Controller.TipoLogradouro.pas',
  SGE.Controller.Promocao in '..\System_SGE\Controller\SGE.Controller.Promocao.pas',
  SGE.Controller.XML_NFeEnviada in '..\System_SGE\Controller\SGE.Controller.XML_NFeEnviada.pas',
  SGE.Controller.XML_NFeImportada in '..\System_SGE\Controller\SGE.Controller.XML_NFeImportada.pas',
  SGE.Controller.CFOP in '..\Sys\Controller\SGE.Controller.CFOP.pas',
  SGE.Controller.Query in '..\Sys\Controller\Query\SGE.Controller.Query.pas',
  SGE.Controller.Query.Factory in '..\Sys\Controller\Query\SGE.Controller.Query.Factory.pas',
  SGE.Controller.Query.Interfaces in '..\Sys\Controller\Query\SGE.Controller.Query.Interfaces.pas',
  SGE.Controller.Impressao.DataModule.ContaAPagar in '..\Sys\Controller\Impressao\DataModule\SGE.Controller.Impressao.DataModule.ContaAPagar.pas' {DataModuleContaAPagar: TDataModule},
  SGE.Controller.Impressao.DataModule.ContaAReceber in '..\Sys\Controller\Impressao\DataModule\SGE.Controller.Impressao.DataModule.ContaAReceber.pas' {DataModuleContaAReceber: TDataModule},
  SGE.Controller.Impressao.DataModule.Cheque in '..\Sys\Controller\Impressao\DataModule\SGE.Controller.Impressao.DataModule.Cheque.pas' {DataModuleCheque: TDataModule},
  SGE.Controller.Impressao.ContaAPagar in '..\Sys\Controller\Impressao\SGE.Controller.Impressao.ContaAPagar.pas',
  SGE.Controller.Impressao.ContaAReceber in '..\Sys\Controller\Impressao\SGE.Controller.Impressao.ContaAReceber.pas',
  SGE.Controller.Impressao.Cheque in '..\Sys\Controller\Impressao\SGE.Controller.Impressao.Cheque.pas',
  Model.Constantes in '..\Sys\Model\Model.Constantes.pas',
  Model.Conexao.Factory.Interfaces in '..\Sys\Model\Conexao\Model.Conexao.Factory.Interfaces.pas',
  Model.Conexao.Factory in '..\Sys\Model\Conexao\Model.Conexao.Factory.pas',
  Model.Conexao.Firedac.Firebird in '..\Sys\Model\Conexao\Model.Conexao.Firedac.Firebird.pas',
  Model.Conexao.Firedac in '..\Sys\Model\Conexao\Model.Conexao.Firedac.pas',
  Model.Conexao.Interfaces in '..\Sys\Model\Conexao\Model.Conexao.Interfaces.pas',
  Model.Entidade.ConfiguracaoINI in '..\Sys\Model\Entidade\Model.Entidade.ConfiguracaoINI.pas',
  Model.Query.Firedac in '..\Sys\Model\Conexao\Model.Query.Firedac.pas',
  Model.Query.Interfaces in '..\Sys\Model\Conexao\Model.Query.Interfaces.pas',
  SGE.Model.Conexao.DataSet in '..\Sys\Model\Conexao\SGE.Model.Conexao.DataSet.pas' {ModelConexaoDataSet: TDataModule},
  SGE.Model.Interacao.DataSet in '..\Sys\Model\Interacao\SGE.Model.Interacao.DataSet.pas',
  UEcfAgil in '..\Sys\lib\UEcfAgil.pas',
  UEcfFactory in '..\Sys\lib\UEcfFactory.pas',
  UEcfGenerico in '..\Sys\lib\UEcfGenerico.pas',
  UEcfWindowsPrinter in '..\Sys\lib\UEcfWindowsPrinter.pas',
  UEcfBematechNaoFiscal in '..\Sys\lib\UEcfBematechNaoFiscal.pas',
  UDMRecursos in '..\Sys\UDMRecursos.pas' {DMRecursos: TDataModule},
  UDMBusiness in '..\Sys\UDMBusiness.pas' {DMBusiness: TDataModule},
  UDMNFe in '..\Sys\UDMNFe.pas' {DMNFe: TDataModule},
  UDMCupom in '..\Sys\UDMCupom.pas' {DMCupom: TDataModule},
  SGE.Model.Dados in '..\Sys\Model\SGE.Model.Dados.pas' {DMDados: TDataModule},
  View.PadraoAbertura in '..\Sys\View\View.PadraoAbertura.pas' {FrmPadraoAbertura},
  View.AutoUpgrade in '..\Sys\View\View.AutoUpgrade.pas' {FrmAutoUpgrade},
  View.Mensagem in '..\Sys\View\View.Mensagem.pas' {FrmMensagem},
  View.Abertura in 'View\View.Abertura.pas' {FrmAbertura},
  View.Login in 'View\View.Login.pas' {FrmLogin},
  View.Esmaecer in '..\Sys\View\View.Esmaecer.pas' {ViewEsmaecer},
  View.InputQuery in '..\Sys\Services\InputQuery\View.InputQuery.pas' {ViewInputQuery},
  View.PadraoCadastro in '..\Sys\View\View.PadraoCadastro.pas' {ViewPadraoCadastro},
  View.PadraoLogin in '..\Sys\View\View.PadraoLogin.pas' {FrmPadraoLogin},
  UPrinc in 'UPrinc.pas' {frmPrinc},
  UGrPadraoCadastro in '..\Sys\lib\UGrPadraoCadastro.pas' {frmGrPadraoCadastro},
  UGrPadrao in '..\Sys\lib\UGrPadrao.pas' {frmGrPadrao},
  UGeBancos in '..\Sys\UGeBancos.pas' {frmGeBancos},
  UGeTipoLogradouro in '..\Sys\UGeTipoLogradouro.pas' {frmGeTipoLogradouro},
  UGeLogradouro in '..\Sys\UGeLogradouro.pas' {frmGeLogradouro},
  UGeEmpresa in '..\Sys\UGeEmpresa.pas' {frmGeEmpresa},
  UGeFornecedor in '..\Sys\UGeFornecedor.pas' {frmGeFornecedor},
  UGeFormaPagto in '..\Sys\UGeFormaPagto.pas' {frmGeFormaPagto},
  UGeVendedor in '..\Sys\UGeVendedor.pas' {frmGeVendedor},
  UGeConfigurarNFeACBr in '..\Sys\UGeConfigurarNFeACBr.pas' {frmGeConfigurarNFeACBr},
  UEnviarLoteNFe in '..\Sys\UEnviarLoteNFe.pas' {frmEnviarLoteNFe},
  UGrCampoRequisitado in '..\Sys\lib\UGrCampoRequisitado.pas' {frmCampoRequisitado},
  UGeGerarBoletos in '..\Sys\UGeGerarBoletos.pas' {frmGeGerarBoleto},
  UGePromocao in '..\Sys\UGePromocao.pas' {frmGePromocao},
  UGeContaCorrente in '..\Sys\UGeContaCorrente.pas' {frmGeContaCorrente},
  UGeCaixa in '..\Sys\UGeCaixa.pas' {frmGeCaixa},
  UGeFluxoCaixa in '..\Sys\UGeFluxoCaixa.pas' {frmGeFluxoCaixa},
  UFuncoes in '..\Sys\lib\UFuncoes.pas',
  UGeExportarNFeGerada in '..\Sys\UGeExportarNFeGerada.pas' {frmGeExportarNFeGerada},
  UGrUsuarioAlterarSenha_v2 in '..\System_SGE\UGrUsuarioAlterarSenha_v2.pas' {frmGrUsuarioAlterarSenha},
  UGrPadraoPesquisa in '..\Sys\lib\UGrPadraoPesquisa.pas' {frmGrPadraoPesquisa},
  UGeConfiguracaoEmpresa in '..\Sys\UGeConfiguracaoEmpresa.pas' {frmGeConfiguracaoEmpresa},
  UObserverInterface in '..\Sys\lib\UObserverInterface.pas',
  UBaseObject in '..\Sys\lib\UBaseObject.pas',
  UCliente in '..\Sys\lib\UCliente.pas',
  UGrPadraoImpressao in '..\System_SGE\lib\UGrPadraoImpressao.pas' {frmGrPadraoImpressao},
  UGeEstoqueAjusteManual in '..\System_SGE\UGeEstoqueAjusteManual.pas' {frmGeEstoqueAjusteManual},
  UGeVenda in '..\Sys\UGeVenda.pas' {frmGeVenda},
  UGeVendaCancelar in '..\Sys\UGeVendaCancelar.pas' {frmGeVendaCancelar},
  UGeVendaConfirmaTitulos in '..\Sys\UGeVendaConfirmaTitulos.pas' {frmGeVendaConfirmaTitulos},
  UGeVendaFormaPagto in '..\Sys\UGeVendaFormaPagto.pas' {frmGeVendaFormaPagto},
  UGeVendaGerarNFe in '..\Sys\UGeVendaGerarNFe.pas' {frmGeVendaGerarNFe},
  UGeEfetuarPagtoREC in '..\Sys\UGeEfetuarPagtoREC.pas' {frmGeEfetuarPagtoREC},
  UGeVendaTransporte in '..\Sys\UGeVendaTransporte.pas' {frmGeVendaTransporte},
  UGrMessage in '..\Sys\lib\UGrMessage.pas' {frmGeMessage},
  UGrUsuarioPerfil in '..\System_SGE\UGrUsuarioPerfil.pas' {frmGrUsuarioPerfil},
  UGrConfigurarAmbiente in '..\Sys\lib\UGrConfigurarAmbiente.pas' {frmGrConfigurarAmbiente},
  UGrUsuarioCopiarPerfil in '..\System_SGE\UGrUsuarioCopiarPerfil.pas' {frmGrUsuarioCopiarPerfil},
  UGeVendaPDV in 'UGeVendaPDV.pas' {frmGeVendaPDV},
  UGeVendaPDVDesconto in 'UGeVendaPDVDesconto.pas' {frmGeVendaPDVDesconto},
  UGeVendaPDVOrcamento in 'UGeVendaPDVOrcamento.pas' {frmGeVendaPDVOrcamento},
  UGrRegistroEstacao in '..\Sys\lib\UGrRegistroEstacao.pas' {FrmGrRegistroEstacao},
  UGeVendaPDVFinalizar in 'UGeVendaPDVFinalizar.pas' {frmGeVendaPDVFinalizar},
  UGeVendaPDVItem in 'UGeVendaPDVItem.pas' {frmGeVendaPDVItem},
  UGrMemo in '..\Sys\lib\UGrMemo.pas' {frmGrMemo},
  UGrMemoData in '..\Sys\lib\UGrMemoData.pas' {frmGrMemoData},
  UGeControleCheque in '..\Sys\UGeControleCheque.pas' {frmGeControleCheque},
  UGeFornecedorClientePesquisa in '..\Sys\UGeFornecedorClientePesquisa.pas' {frmGeFornecedorClientePesquisa},
  UGeVendaPDVFormaPagto in 'UGeVendaPDVFormaPagto.pas' {frmGeVendaPDVFormaPagto},
  UGeConsultarLoteNFe_v2 in '..\System_SGE\UGeConsultarLoteNFe_v2.pas' {frmGeConsultarLoteNFe_v2},
  UGrUsuario in '..\System_SGE\UGrUsuario.pas' {frmGrUsuario},
  View.Usuario.AlterarSenha in '..\Sys\View\View.Usuario.AlterarSenha.pas' {ViewUsuarioAlterarSenha},
  View.Usuario in '..\Sys\View\View.Usuario.pas' {ViewUsuario},
  View.Usuario.Perfil in '..\Sys\View\View.Usuario.Perfil.pas' {ViewUsuarioPerfil},
  View.CampoRequisitado in '..\Sys\View\View.CampoRequisitado.pas' {ViewCampoRequisitado},
  View.WaitAMoment in '..\Sys\View\View.WaitAMoment.pas' {ViewWaitAMoment},
  View.Certificado in '..\Sys\View\View.Certificado.pas' {ViewCertificado},
  View.Produto in '..\Sys\View\View.Produto.pas' {ViewProduto},
  View.FabricanteProduto in '..\Sys\View\View.FabricanteProduto.pas' {ViewFabricanteProduto},
  View.GrupoProduto in '..\Sys\View\View.GrupoProduto.pas' {ViewGrupoProduto},
  View.SecaoProduto in '..\Sys\View\View.SecaoProduto.pas' {ViewSecaoProduto},
  View.UnidadeProduto in '..\Sys\View\View.UnidadeProduto.pas' {ViewUnidadeProduto},
  View.CFOP in '..\Sys\View\View.CFOP.pas' {ViewCFOP},
  View.IBPT in '..\Sys\View\View.IBPT.pas' {ViewIBPT},
  View.IBPT.Importar in '..\Sys\View\View.IBPT.Importar.pas' {ViewIBPTImportar},
  View.Servico.ConsultarCNPJ in '..\Sys\View\View.Servico.ConsultarCNPJ.pas' {ViewServicoConsultarCNPJ},
  View.Cliente in '..\Sys\View\View.Cliente.pas' {ViewCliente},
  View.CondicaoPagto in '..\Sys\View\View.CondicaoPagto.pas' {ViewCondicaoPagto},
  View.Memo in '..\Sys\View\View.Memo.pas' {ViewMemo},
  View.MemoData in '..\Sys\View\View.MemoData.pas' {ViewMemoData},
  View.ContaAPagar in '..\Sys\View\View.ContaAPagar.pas' {ViewContaAPagar},
  View.ContaAPagar.Pagamento in '..\Sys\View\View.ContaAPagar.Pagamento.pas' {ViewContaAPagarPagamento},
  View.ContaAReceber in '..\Sys\View\View.ContaAReceber.pas' {ViewContaAReceber},
  View.ContaAReceber.Pagamento in '..\Sys\View\View.ContaAReceber.Pagamento.pas' {ViewContaAReceberPagamento},
  View.Cidade in '..\Sys\View\View.Cidade.pas' {ViewCidade},
  View.Distrito in '..\Sys\View\View.Distrito.pas' {ViewDistrito},
  View.Estado in '..\Sys\View\View.Estado.pas' {ViewEstado},
  View.Logradouro in '..\Sys\View\View.Logradouro.pas' {ViewLogradouro},
  View.Bairro in '..\Sys\View\View.Bairro.pas' {ViewBairro},
  View.Cheque in '..\Sys\View\View.Cheque.pas' {ViewCheque},
  View.PadraoPesquisa in '..\Sys\View\View.PadraoPesquisa.pas' {ViewPadraoPesquisa},
  View.Query.FornecedorCliente in '..\Sys\View\Query\View.Query.FornecedorCliente.pas' {ViewQueryFornecedorCliente};

{$R *.res}

begin
  FileINI := TIniFile.Create( ExtractFilePath(ParamStr(0)) + 'Conexao.ini' );

  Application.Initialize;
  Application.Title := 'PDV | Ponto de Venda do SGE/SGI';

  SplashShow(Application);

  Application.CreateForm(TDMRecursos, DMRecursos);
  Application.CreateForm(TDMBusiness, DMBusiness);
  Application.CreateForm(TDMNFe, DMNFe);
  Application.CreateForm(TDMDados, DMDados);
  SplashFree;

  if ExecutarLogin() then
    Application.CreateForm(TfrmPrinc, frmPrinc);

  Application.Run;
end.
